#!/bin/bash

echo "🔧 Ubuntu Port Fix Commands"
echo "=========================="
echo ""
echo "Run these commands in order:"
echo ""
echo "# 1. Start Nginx (since it's stopped)"
echo "sudo systemctl start nginx"
echo ""
echo "# 2. Check if Nginx started successfully"
echo "sudo systemctl status nginx"
echo ""
echo "# 3. If Nginx failed to start, check what's on port 3025"
echo "sudo lsof -i :3025"
echo ""
echo "# 4. Test Nginx configuration"
echo "sudo nginx -t"
echo ""
echo "# 5. Check the updated configuration"
echo "grep -n 'listen' /etc/nginx/sites-available/nullsector-dashboard"
echo ""
echo "# 6. Restart API service"
echo "sudo systemctl start nullsector-calculator-api"
echo ""
echo "# 7. Check everything is running"
echo "sudo systemctl status nginx"
echo "sudo systemctl status nullsector-calculator-api"
echo ""
echo "# 8. Test the new endpoint"
echo "curl -I http://localhost:3025"
echo ""
echo "# If port 3025 is in use, try port 3026 instead:"
echo "sudo sed -i 's/listen 3025/listen 3026/g' /etc/nginx/sites-available/nullsector-dashboard"
echo "sudo sed -i 's/listen \[::\]:3025/listen \[::\]:3026/g' /etc/nginx/sites-available/nullsector-dashboard"
